---
- name: Attente libération lock apt
  shell: |
    while fuser /var/lib/dpkg/lock-frontend \
                /var/lib/apt/lists/lock \
                /var/cache/apt/archives/lock \
                >/dev/null 2>&1; do sleep 5; done
  timeout: 300

- name: Mise à jour des paquets
  apt:
    update_cache: yes
    upgrade: dist

- name: Installation des outils de base
  apt:
    name:
      - vim
      - curl
      - iproute2 
      - htop
      - python3
    state: present

- name: Configuration du timezone
  timezone:
    name: Europe/Paris
