all:
  vars:
    ansible_user: debian
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519

  children:
    lan:
      hosts:
        srvlan:
          ansible_host: 192.168.100.173
        vm1:
          ansible_host: 192.168.100.244
        vm2:
          ansible_host: 192.168.100.171

    dmz:
      hosts:
        srvdmz:
          ansible_host: 192.168.100.39
