---
- name: Installation d Open vSwitch et ifupdown
  apt:
    name:
      - openvswitch-switch
      - ifupdown
    state: present
    update_cache: yes

- name: Verification du service openvswitch-switch
  systemd:
    name: openvswitch-switch
    state: started
    enabled: yes

- name: Suppression config systemd-networkd br0
  file:
    path: /etc/systemd/network/10-br0.network
    state: absent
  notify: restart networkd

- name: Configuration OVS via interfaces
  copy:
    dest: /etc/network/interfaces
    content: |
      source /etc/network/interfaces.d/*

      auto lo
      iface lo inet loopback

      ## Configuration Open vSwitch
      auto br0
      allow-ovs br0
      iface br0 inet static
        address 192.168.3.15
        netmask 255.255.255.0
        gateway 192.168.3.1
        ovs_type OVSBridge
        ovs_ports ens4 br0-patch0

      allow-br0 ens4
      iface ens4 inet manual
        ovs_bridge br0
        ovs_type OVSPort

      allow-br0 br0-patch0
      iface br0-patch0 inet manual
        ovs_bridge br0
        ovs_type OVSPatchPort
        ovs_patch_peer br1-patch0

      auto br1
      allow-ovs br1
      iface br1 inet manual
        ovs_type OVSBridge
        ovs_ports ens5 br1-patch0 br1-patch1

      allow-br1 ens5
      iface ens5 inet manual
        ovs_bridge br1
        ovs_type OVSPort

      allow-br1 br1-patch0
      iface br1-patch0 inet manual
        ovs_bridge br1
        ovs_type OVSPatchPort
        ovs_patch_peer br0-patch0

      allow-br1 br1-patch1
      iface br1-patch1 inet manual
        ovs_bridge br1
        ovs_type OVSPatchPort
        ovs_patch_peer br2-patch0

      auto br2
      allow-ovs br2
      iface br2 inet manual
        ovs_type OVSBridge
        ovs_ports ens6 br2-patch0

      allow-br2 ens6
      iface ens6 inet manual
        ovs_bridge br2
        ovs_type OVSPort

      allow-br2 br2-patch0
      iface br2-patch0 inet manual
        ovs_bridge br2
        ovs_type OVSPatchPort
        ovs_patch_peer br1-patch1

- name: Service networking-restart pour OVS au boot
  copy:
    dest: /etc/systemd/system/networking-restart.service
    content: |
      [Unit]
      Description=Redemarrage du service networking
      After=network.target openvswitch-switch.service

      [Service]
      Type=oneshot
      ExecStart=/bin/sleep 6
      ExecStart=/sbin/service networking restart
      RemainAfterExit=true

      [Install]
      WantedBy=multi-user.target

- name: Activation networking-restart
  systemd:
    name: networking-restart
    enabled: yes
    daemon_reload: yes

- name: Restart networking pour appliquer OVS
  shell: ifdown -a --allow=ovs 2>/dev/null; ifup -a --allow=ovs
  changed_when: true
