---
- name: Installation d Open vSwitch
  apt:
    name:
      - openvswitch-switch
      - ifupdown
    state: present
    update_cache: yes

- name: Verification du service openvswitch-switch
  systemd:
    name: openvswitch-switch
    state: started
    enabled: yes

- name: Configuration OVS via /etc/network/interfaces
  copy:
    dest: /etc/network/interfaces
    content: |
      auto lo
      iface lo inet loopback

      auto br0
      allow-ovs br0
      iface br0 inet static
        address 192.168.3.15
        netmask 255.255.255.0
        gateway 192.168.3.1
        ovs_type OVSBridge
        ovs_ports ens4 br0-patch0

      allow-br0 ens4
      iface ens4 inet manual
        ovs_bridge br0
        ovs_type OVSPort

      allow-br0 br0-patch0
      iface br0-patch0 inet manual
        ovs_bridge br0
        ovs_type OVSPatchPort
        ovs_patch_peer br1-patch0

      auto br1
      allow-ovs br1
      iface br1 inet manual
        ovs_type OVSBridge
        ovs_ports ens5 br1-patch0 br1-patch1

      allow-br1 ens5
      iface ens5 inet manual
        ovs_bridge br1
        ovs_type OVSPort

      allow-br1 br1-patch0
      iface br1-patch0 inet manual
        ovs_bridge br1
        ovs_type OVSPatchPort
        ovs_patch_peer br0-patch0

      allow-br1 br1-patch1
      iface br1-patch1 inet manual
        ovs_bridge br1
        ovs_type OVSPatchPort
        ovs_patch_peer br2-patch0

      auto br2
      allow-ovs br2
      iface br2 inet manual
        ovs_type OVSBridge
        ovs_ports ens6 br2-patch0

      allow-br2 ens6
      iface ens6 inet manual
        ovs_bridge br2
        ovs_type OVSPort

      allow-br2 br2-patch0
      iface br2-patch0 inet manual
        ovs_bridge br2
        ovs_type OVSPatchPort
        ovs_patch_peer br1-patch1
  notify: restart networking

- name: Ports patch br0 br1 et br1 br2
  command: >
    ovs-vsctl
    -- --may-exist add-port br0 br0-patch0
    -- set interface br0-patch0 type=patch options:peer=br1-patch0
    -- --may-exist add-port br1 br1-patch0
    -- set interface br1-patch0 type=patch options:peer=br0-patch0
    -- --may-exist add-port br1 br1-patch1
    -- set interface br1-patch1 type=patch options:peer=br2-patch0
    -- --may-exist add-port br2 br2-patch0
    -- set interface br2-patch0 type=patch options:peer=br1-patch1
  changed_when: false
