---
- include_tasks: srvlan.yml
  when: inventory_hostname == "srvlan"

- include_tasks: srvdmz.yml
  when: inventory_hostname == "srvdmz"

- include_tasks: vm.yml
  when: inventory_hostname in ["vm1", "vm2"]
