---
- name: Installation NetworkManager
  apt:
    name: network-manager
    state: present

- name: Configuration IP fixe interface DMZ
  community.general.nmcli:
    conn_name: dmz
    ifname: ens4
    type: ethernet
    ip4: "{{ srvdmz_ip }}/{{ srvdmz_mask }}"
    routes4:
      - ip: "192.168.2.0/24"
        next_hop: "192.168.4.1"
    state: present
    autoconnect: true
 
