---
- name: Installation NetworkManager
  apt:
    name: network-manager
    state: present

- name: Configuration IP fixe interface DMZ
  community.general.nmcli:
    conn_name: dmz
    ifname: ens4
    type: ethernet
    ip4: "{{ srvdmz_ip }}/{{ srvdmz_mask }}"
    routes4:
      - "192.168.2.0/24 192.168.4.1"
    state: present
    autoconnect: true

- name: Activation connexion DMZ
  command: nmcli connection up dmz
  changed_when: false
  ignore_errors: yes 
