---
- name: Installation NetworkManager
  apt:
    name: network-manager
    state: present

- name: Configuration IP fixe interface LAN
  community.general.nmcli:
    conn_name: lan
    ifname: "{{ iface_lan }}"
    type: ethernet
    ip4: "{{ srvlan_lan_ip }}/{{ srvlan_lan_mask }}"
    state: present
    autoconnect: true

- name: Configuration IP fixe interface GREEN
  community.general.nmcli:
    conn_name: green
    ifname: "{{ iface_green }}"
    type: ethernet
    ip4: "{{ srvlan_green_ip }}/{{ srvlan_green_mask }}"
    state: present
    autoconnect: true
    routes4:
      - ip: "192.168.4.0/24"
        next_hop: "{{ srvlan_gateway }}"

- name: Activation du routage ip_forward
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Installation iptables-persistent
  apt:
    name:
      - iptables-persistent
      - netfilter-persistent
    state: present

- name: Règle NAT MASQUERADE
  ansible.builtin.iptables:
    table: nat
    chain: POSTROUTING
    out_interface: "{{ iface_bootstrap }}"
    jump: MASQUERADE

- name: Sauvegarde règles iptables
  shell: iptables-save > /etc/iptables/rules.v4
