---
# Interfaces
iface_bootstrap: ens3
iface_lan: ens4
iface_green: ens5
iface_dmz: ens6

# Adresses IP fixes
srvlan_lan_ip: 192.168.3.1
srvlan_lan_mask: 24
srvlan_green_ip: 192.168.2.2
srvlan_green_mask: 24
srvlan_dmz_ip: 192.168.4.2
srvlan_dmz_mask: 24
srvlan_gateway: 192.168.2.1
# IPs fixes vm1/vm2
vm1_lan_ip: 192.168.3.2
vm2_lan_ip: 192.168.3.4
